const ActionTypes = {
    COURSE_LIST_LOAD: 'COURSE_LIST_LOAD',
    COURSE_LIST_LOAD_SUCCESS: 'COURSE_LIST_LOAD_SUCCESS',
    COURSE_LIST_LOAD_ERROR: 'COURSE_LIST_LOAD_ERROR',
};

export default ActionTypes;