const ActionTypes = {
    SET_PROFILE: 'SET_PROFILE',
    SET_PROFILE_SUCCESS: 'SET_PROFILE_SUCCESS',
    SET_PROFILE_ERROR: 'SET_PROFILE_ERROR',

    ADD_PROFILE_COURSE: 'ADD_PROFILE_COURSE',
};

export {
    ActionTypes,
};